### ISSUE TITLE
NSX-T 2.4 `Invalid value 'nsx-manager' specified for property nsx_role`

### ISSUE THREAD

**Issue by cunnie** [vmware/nsx-t-datacenter-ci-pipelines#27]
NSX-T 2.4 install will not succeed because NSX-T has introduced a new role, `nsx-manager nsx-controller`, previously `nsx-manager` was adequate.

See <https://docs.vmware.com/en/VMware-NSX-T-Data-Center/2.4/nsxt_24_install.pdf> and search for the section, _Install NSX Manager on ESXi Using the Command-Line OVF Tool_. In particular, look for `--prop:nsx_role`

Error:

> "msg": "Failed to deploy OVA, error message from ovftool is: Opening OVA source: http://10.0.2.15:40001/nsx-unified-appliance-2.4.0.0.0.12456291.ova\nThe manifest does not validate\nOpening VI target: vi://administrator%40vsphere.local@10.193.176.11:443//Datacenter/host/Cluster/\nError:\n - Invalid value 'nsx-manager' specified for property nsx_role.\nCompleted with errors\n, the comand was ['/usr/bin/ovftool', '--acceptAllEulas', '--skipManifestCheck', '--X:injectOvfEnv', '--powerOn', '--noSSLVerify', '--allowExtraConfig', '--diskMode=thin', '--datastore=LUN01', '--name=nsxt-manager', '--network=VM Network', '--prop:nsx_hostname=nsxmgr-01.haas-104.pez.pivotal.io', '--prop:nsx_dns1_0=10.193.176.2', '--prop:nsx_domain_0=haas-104.pez.pivotal.io', '--prop:nsx_ntp_0=10.193.176.2', '--prop:nsx_gateway_0=10.193.176.1', '--prop:nsx_ip_0=10.193.176.20', '--prop:nsx_netmask_0=255.255.255.0', '--prop:nsx_passwd_0=********', '--prop:nsx_cli_passwd_0=********', '--prop:nsx_isSSHEnabled=True', '--prop:nsx_allowSSHRootLogin=True', '--prop:nsx_role=nsx-manager', 'http://10.0.2.15:40001/nsx-unified-appliance-2.4.0.0.0.12456291.ova', 'vi://administrator@vsphere.local:********@10.193.176.11//Datacenter/host/Cluster/']"

**Comment by kais66** [comment]
thanks @cunnie for raising this issue and the fix. It's already WIP to update the pipeline to support 2.4 installation and we're trying to push a PR with updated image by end of this week. We will try to be backward compatible.

cc @Dyanngg

**Comment by Dyanngg** [comment]
@cunnie  We are tracking this issue in new branch 'unified appliance'. Will update when the branch is merged. Thanks for bringing it up!

**Comment by rbales79** [comment]
did this get resolved with the recent image update? I think i'm hitting the same wall using nsx-t-install-03112019.tar

fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to deploy OVA, error message from ovftool is: Opening OVA source: http://10.0.102.82/nsx-unified-appliance-2.4.0.0.0.12456291.ova\nThe manifest does not validate\nOpening VI target: vi://administrator%40ilab.vsphere.local@10.0.1.5:443//iLab%20Virtual%20Datacenter/host/iLab%20vSphere%20Cluster/\nError: Fault cause: vmodl.fault.InvalidArgument\n\nWarning:\n - DeploymentOption Configuration: 'SMALL' does not exists.\nCompleted with errors\n, the comand was ['/usr/bin/ovftool', '--acceptAllEulas', '--skipManifestCheck', '--X:injectOvfEnv', '--powerOn', '--noSSLVerify', '--allowExtraConfig', '--diskMode=thin', '--datastore=VS_V7K-vSphere_VMFS_Volume', '--name=nsxt-manager', '--network=ilab-mgmt-vlan-1', '--deploymentOption=SMALL', '--prop:nsx_hostname=nsxt-manager-1.ilab.dti', '--prop:nsx_dns1_0=10.0.1.2', '--prop:nsx_domain_0=ilab.dti', '--prop:nsx_ntp_0=time.vmware.com', '--prop:nsx_gateway_0=10.0.1.1', '--prop:nsx_ip_0=10.0.1.112', '--prop:nsx_netmask_0=255.255.255.0', '--prop:nsx_passwd_0=****************', '--prop:nsx_cli_passwd_0=****************', '--prop:nsx_isSSHEnabled=True', '--prop:nsx_allowSSHRootLogin=True', '--prop:nsx_role=nsx-manager', 'http://10.0.102.82/nsx-unified-appliance-2.4.0.0.0.12456291.ova', 'vi://administrator@ilab.vsphere.local:********@10.0.1.5//iLab Virtual Datacenter/host/iLab vSphere Cluster/']"}
	to retry, use: --limit @/tmp/build/6fab756d/nsxt-ansible/basic_topology.retry

**Comment by rbales79** [comment]
any update on this? or what the plan is for 2.4 merging to master etc? 

it looks like the docker-image is hardcoded to pull from the master branch in run.sh, which is why it's still giving the issue with with the property.

'''
unified_appliance=true
version_num=$(echo $nsxt_version | cut -d'.' -f1)
version_sub_num=$(echo $nsxt_version | cut -d'.' -f2)
if [[ $version_num -le 2 ]] && [[ $version_sub_num -le 3 ]]; then
    unified_appliance=false
fi

nsx_t_pipeline_branch=master
nsxt_ansible_branch=v1.0.0

if [[ $PIPELINE_BRANCH != "" ]]; then
	nsx_t_pipeline_branch=$PIPELINE_BRANCH
fi
if [[ $unified_appliance ]]; then
    nsxt_ansible_branch=master
fi
'''

**Comment by Dyanngg** [comment]
@rbales79 This 'unified_appliance' branch is still under testing. If you plan to deploy NSX-T 2.3.0 and earlier you should use the master pipeline branch. If you are trying to deploy NSX-T 2.4.0, in the 'unified_appliance' branch of the pipeline the role should already been fixed to controller+manager. And for that to work we need to pull nsxt_ansible from the master branch, rather than v1.0.0

**Comment by rbales79** [comment]
@Dyanngg   Deploying 2.4 using the unified_pipeline branch image. 

However as noted above the pipeline_branch variable was commented out, and doesn't get set anywhere else during image creation. Hence the image is running with the correct version of nsxt_ansible because unified_appliance is set to true, but it's still pulling code from master for the pipeline setup, causing it to still provide the same error above.

  As a test, i forked the unified_appliance branch, uncommented and set PIPELINE_BRANCH="unified_appliance" in run.sh, created a repo on dockerhub, and set it to autobuild the docker image anytime i push to the git repo. 

  it works perfectly fine on the image I built with the variable configured properly.

**Comment by Dyanngg** [comment]
@rbales79 you could simply add environment variable when executing docker run: 
```
docker run  ...  -e PIPELINE_BRANCH='unified_appliance' ... nsx-t-install.
```
