### ISSUE TITLE
Getting 404 on referenced links and tar file 

### ISSUE THREAD

**Issue by elgwhoppo** [vmware/nsx-t-datacenter-ci-pipelines#37]
https://github.com/vmware/nsx-t-datacenter-ci-pipelines/blob/master/docker_image/nsx-t-install-09122018.tar?raw=true
https://github.com/vmware/nsx-t-datacenter-ci-pipelines/blob/master/pipelines/sample-params.yml

Is this cocourse project still a viable method of prepping NSX-T for PKS or are there other projects we should leverage?

**Comment by rbales79** [comment]
This project is absolutely viable, the way the image is distributed leaves a lot to be desired and I've created an issue for that. 

You have to look in the docker_image directory of the branch you're deploying to get the appropriate file name for the tar file. Each time they upload the stamp it with the date.

I have the image on dockerhub with the latest pushes for master and nsxt_2.4.0 branches. I think i posted info under the issue to create the image pipeline to docker hub on what i did, and you should be able to use that in order to skip the step for downloading and importing the image.

Feel free to reach out if you need help, and as a side note, I am in no way affiliated with VMware, anything I do or provide is best effort!

**Comment by elgwhoppo** [comment]
Got it, will do. Thx for posting up @rbales79!
